#!/bin/bash

asan=0
clang=1

if [ -f VERSION ]
then
  version_file=VERSION
fi

if [ -f MYSQL_VERSION ]
then
  if [ "$version_file" != "" ]
  then
    echo "Error! Both VERSION and MYSQL_VERSION exist!"
    exit 1
  fi
  version_file=MYSQL_VERSION
fi

major_version=$(sed -n 's,MYSQL_VERSION_MAJOR=,,p' $version_file)
minor_version=$(sed -n 's,MYSQL_VERSION_MINOR=,,p' $version_file)

echo "Building version ${major_version}.${minor_version}"

if [ "$major_version.$minor_version" == "8.4" ] || \
   [ "$major_verion" -ge "9" ]
then
  build_home="build"
else
  build_home="build.dir"
fi

version=$1
build_type=${2:-Debug}
build_dir=${3:-${build_home}/${build_type,,}}

echo "build type ${build_type}"
echo "build dir ${build_dir}"

if [ "$clang" == "1" ]; then
   clang_opt="-DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18"
fi

if [ "$asan" == 1 ]; then
  asan_opt="-DWITH_ASAN=ON"
  build_dir=${build_dir}.asan
fi

if [[ "$(uname -m)" != "aarch64" ]]; then
   mold_opt="-DWITH_LD=mold"
fi

cmd="cmake -B ${build_dir} -GNinja -DCMAKE_BUILD_TYPE=$build_type \
     -DDOWNLOAD_BOOST=1 -DWITH_BOOST=~/boost \
     -DWITH_AUTHENTICATION_LDAP=OFF -DWITH_PERCONA_AUTHENTICATION_LDAP=OFF \
     -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DFORCE_COLORED_OUTPUT=ON \
     $mold_opt \
     -DWITH_ROCKSDB=OFF \
     -DWITH_COREDUMPER=OFF \
     -DWITHOUT_COMPONENT_KEYRING_KMIP=ON \
     $clang_opt \
     $asan_opt"

echo $cmd

cat > .clangd <<EOF
CompileFlags:
  CompilationDatabase: ${build_dir}
EOF

${cmd} && time ninja -C "$build_dir" -j10
