#!/bin/bash

asan=0
clang=1

if [ -f VERSION ]
then
  version_file=VERSION
fi

if [ -f MYSQL_VERSION ]
then
  if [ "$version_file" != "" ]
  then
    echo "Error! Both VERSION and MYSQL_VERSION exist!"
    exit 1
  fi
  version_file=MYSQL_VERSION
fi

major_version=$(sed -n 's,MYSQL_VERSION_MAJOR=,,p' $version_file)
minor_version=$(sed -n 's,MYSQL_VERSION_MINOR=,,p' $version_file)
patch_version=$(sed -n 's,MYSQL_VERSION_PATCH=,,p' $version_file)

echo "Building version ${major_version}.${minor_version}.${patch_version}"

build_home="build"

build_type=${1:-Debug}
build_dir=${2:-${build_home}/${build_type,,}}

echo "build type ${build_type}"
echo "build dir ${build_dir}"

if [ "$asan" == 1 ]; then
  asan_opt="-DWITH_ASAN=ON"
  build_dir=${build_dir}.asan
fi

if [[ "$(uname -m)" != "aarch64" ]]; then
   mold_opt="-DWITH_LD=mold"
fi

version_num=$((major_version * 10000 + minor_version * 100 + patch_version))

if [[ $version_num -ge 50700 ]]; then
  echo "Avoiding clang on 5.7"
  clang=0
fi

if [[ $version_num -ge 80028 ]]; then
  v80028opt="-DWITHOUT_COMPONENT_KEYRING_KMIP=ON"
fi

if [[ $version_num -ge 80029 ]]; then
  v80029opt="-DWITH_ROCKSDB=OFF -DWITH_COREDUMPER=OFF"
fi

if [[ $version_num -ge 80030 ]]; then
  v80030opt="-DWITH_PERCONA_AUTHENTICATION_LDAP=OFF"
fi

if [[ $version_num -ge 80033 ]]; then
  v80033opt="-DFORCE_COLORED_OUTPUT=ON"
fi

if [ "$clang" == "1" ]; then
   compiler_opt="-DCMAKE_C_COMPILER=clang-18 -DCMAKE_CXX_COMPILER=clang++-18"
fi

cmd="cmake -B ${build_dir} -GNinja -DCMAKE_BUILD_TYPE=$build_type \
     -DDOWNLOAD_BOOST=1 -DWITH_BOOST=~/boost \
     -DWITH_AUTHENTICATION_LDAP=OFF \
     -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
     $mold_opt \
     $v80028opt \
     $v80029opt \
     $v80030opt \
     $v80033opt \
     $compiler_opt \
     $asan_opt"

echo $cmd

cat > .clangd <<EOF
CompileFlags:
  CompilationDatabase: ${build_dir}
EOF

${cmd} && time ninja -C "$build_dir" -j10
